$axure.loadCurrentPage({
  "url":"机构关联.html",
  "generationDate":new Date(1489416226029.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b96e63e63f474e37b384160a21d9fcc6",
    "type":"Axure:Page",
    "name":"机构关联",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0dfcd4bc481c4bf897fd50c6cad9e868",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":515}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7d6287cc10841729fb76f9075f73b69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":515}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机构关联/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0dfcd4bc481c4bf897fd50c6cad9e868":{
      "scriptId":"u0"},
    "e7d6287cc10841729fb76f9075f73b69":{
      "scriptId":"u1"}}});