//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace TAHB.Model
{
    /// <summary>
    /// 实体类_directories。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("_directories")]
    [Serializable]
    public partial class _directories : Entity
    {
        #region Model
		private int _id;
		private string _type;
		private string _source;
		private string _code;
		private string _explain;
		private string _character;
		private string _other;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 废物类别
		/// </summary>
		[Field("type")]
		public string type
		{
			get{ return _type; }
			set
			{
				this.OnPropertyValueChange("type");
				this._type = value;
			}
		}
		/// <summary>
		/// 行业来源
		/// </summary>
		[Field("source")]
		public string source
		{
			get{ return _source; }
			set
			{
				this.OnPropertyValueChange("source");
				this._source = value;
			}
		}
		/// <summary>
		/// 废物代码
		/// </summary>
		[Field("code")]
		public string code
		{
			get{ return _code; }
			set
			{
				this.OnPropertyValueChange("code");
				this._code = value;
			}
		}
		/// <summary>
		/// 危险废物
		/// </summary>
		[Field("explain")]
		public string explain
		{
			get{ return _explain; }
			set
			{
				this.OnPropertyValueChange("explain");
				this._explain = value;
			}
		}
		/// <summary>
		/// 危险特性
		/// </summary>
		[Field("character")]
		public string character
		{
			get{ return _character; }
			set
			{
				this.OnPropertyValueChange("character");
				this._character = value;
			}
		}
		/// <summary>
		/// 其他
		/// </summary>
		[Field("other")]
		public string other
		{
			get{ return _other; }
			set
			{
				this.OnPropertyValueChange("other");
				this._other = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.type,
				_.source,
				_.code,
				_.explain,
				_.character,
				_.other,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._type,
				this._source,
				this._code,
				this._explain,
				this._character,
				this._other,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "_directories");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "_directories", "");
            /// <summary>
			/// 废物类别
			/// </summary>
			public readonly static Field type = new Field("type", "_directories", "废物类别");
            /// <summary>
			/// 行业来源
			/// </summary>
			public readonly static Field source = new Field("source", "_directories", "行业来源");
            /// <summary>
			/// 废物代码
			/// </summary>
			public readonly static Field code = new Field("code", "_directories", "废物代码");
            /// <summary>
			/// 危险废物
			/// </summary>
			public readonly static Field explain = new Field("explain", "_directories", "危险废物");
            /// <summary>
			/// 危险特性
			/// </summary>
			public readonly static Field character = new Field("character", "_directories", "危险特性");
            /// <summary>
			/// 其他
			/// </summary>
			public readonly static Field other = new Field("other", "_directories", "其他");
        }
        #endregion
	}
}