//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace TAHB.Model
{
    /// <summary>
    /// 实体类_freedirectories。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("_freedirectories")]
    [Serializable]
    public partial class _freedirectories : Entity
    {
        #region Model
		private int _id;
		private string _typeorcode;
		private string _explain;
		private string _freelink;
		private string _freewhere;
		private string _freecontent;
		private string _other;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("typeorcode")]
		public string typeorcode
		{
			get{ return _typeorcode; }
			set
			{
				this.OnPropertyValueChange("typeorcode");
				this._typeorcode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("explain")]
		public string explain
		{
			get{ return _explain; }
			set
			{
				this.OnPropertyValueChange("explain");
				this._explain = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("freelink")]
		public string freelink
		{
			get{ return _freelink; }
			set
			{
				this.OnPropertyValueChange("freelink");
				this._freelink = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("freewhere")]
		public string freewhere
		{
			get{ return _freewhere; }
			set
			{
				this.OnPropertyValueChange("freewhere");
				this._freewhere = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("freecontent")]
		public string freecontent
		{
			get{ return _freecontent; }
			set
			{
				this.OnPropertyValueChange("freecontent");
				this._freecontent = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("other")]
		public string other
		{
			get{ return _other; }
			set
			{
				this.OnPropertyValueChange("other");
				this._other = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.typeorcode,
				_.explain,
				_.freelink,
				_.freewhere,
				_.freecontent,
				_.other,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._typeorcode,
				this._explain,
				this._freelink,
				this._freewhere,
				this._freecontent,
				this._other,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "_freedirectories");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "_freedirectories", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field typeorcode = new Field("typeorcode", "_freedirectories", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field explain = new Field("explain", "_freedirectories", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field freelink = new Field("freelink", "_freedirectories", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field freewhere = new Field("freewhere", "_freedirectories", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field freecontent = new Field("freecontent", "_freedirectories", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field other = new Field("other", "_freedirectories", "");
        }
        #endregion
	}
}