//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace TAHB.Model
{
    /// <summary>
    /// 实体类_functioninfo。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("_functioninfo")]
    [Serializable]
    public partial class _functioninfo : Entity
    {
        #region Model
		private int _id;
		private string _name;
		private string _displayname;
		private string _actionname;
		private string _controllername;
		private string _description;
		private int? _fatherid;
		private int? _level;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("name")]
		public string name
		{
			get{ return _name; }
			set
			{
				this.OnPropertyValueChange("name");
				this._name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("displayname")]
		public string displayname
		{
			get{ return _displayname; }
			set
			{
				this.OnPropertyValueChange("displayname");
				this._displayname = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("actionname")]
		public string actionname
		{
			get{ return _actionname; }
			set
			{
				this.OnPropertyValueChange("actionname");
				this._actionname = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("controllername")]
		public string controllername
		{
			get{ return _controllername; }
			set
			{
				this.OnPropertyValueChange("controllername");
				this._controllername = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("description")]
		public string description
		{
			get{ return _description; }
			set
			{
				this.OnPropertyValueChange("description");
				this._description = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("fatherid")]
		public int? fatherid
		{
			get{ return _fatherid; }
			set
			{
				this.OnPropertyValueChange("fatherid");
				this._fatherid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("level")]
		public int? level
		{
			get{ return _level; }
			set
			{
				this.OnPropertyValueChange("level");
				this._level = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.name,
				_.displayname,
				_.actionname,
				_.controllername,
				_.description,
				_.fatherid,
				_.level,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._name,
				this._displayname,
				this._actionname,
				this._controllername,
				this._description,
				this._fatherid,
				this._level,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "_functioninfo");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "_functioninfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field name = new Field("name", "_functioninfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field displayname = new Field("displayname", "_functioninfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field actionname = new Field("actionname", "_functioninfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field controllername = new Field("controllername", "_functioninfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field description = new Field("description", "_functioninfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field fatherid = new Field("fatherid", "_functioninfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field level = new Field("level", "_functioninfo", "");
        }
        #endregion
	}
}