//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace TAHB.Model
{
    /// <summary>
    /// 实体类_userinfo。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("_userinfo")]
    [Serializable]
    public partial class _userinfo : Entity
    {
        #region Model
		private long _id;
		private string _name;
		private string _realname;
		private string _pwd;
		private DateTime _regtime;
		private DateTime? _endtime;
		private DateTime? _lastlogdate;
		private string _phone;
		private string _tel;
		private string _email;
		private string _address;
		private string _uid;
		private int? _online;
		private int? _userlock;
		private int? _roleid;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public long id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("name")]
		public string name
		{
			get{ return _name; }
			set
			{
				this.OnPropertyValueChange("name");
				this._name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("realname")]
		public string realname
		{
			get{ return _realname; }
			set
			{
				this.OnPropertyValueChange("realname");
				this._realname = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("pwd")]
		public string pwd
		{
			get{ return _pwd; }
			set
			{
				this.OnPropertyValueChange("pwd");
				this._pwd = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("regtime")]
		public DateTime regtime
		{
			get{ return _regtime; }
			set
			{
				this.OnPropertyValueChange("regtime");
				this._regtime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("endtime")]
		public DateTime? endtime
		{
			get{ return _endtime; }
			set
			{
				this.OnPropertyValueChange("endtime");
				this._endtime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("lastlogdate")]
		public DateTime? lastlogdate
		{
			get{ return _lastlogdate; }
			set
			{
				this.OnPropertyValueChange("lastlogdate");
				this._lastlogdate = value;
			}
		}
		/// <summary>
		/// 手机号
		/// </summary>
		[Field("phone")]
		public string phone
		{
			get{ return _phone; }
			set
			{
				this.OnPropertyValueChange("phone");
				this._phone = value;
			}
		}
		/// <summary>
		/// 固话
		/// </summary>
		[Field("tel")]
		public string tel
		{
			get{ return _tel; }
			set
			{
				this.OnPropertyValueChange("tel");
				this._tel = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("email")]
		public string email
		{
			get{ return _email; }
			set
			{
				this.OnPropertyValueChange("email");
				this._email = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("address")]
		public string address
		{
			get{ return _address; }
			set
			{
				this.OnPropertyValueChange("address");
				this._address = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("uid")]
		public string uid
		{
			get{ return _uid; }
			set
			{
				this.OnPropertyValueChange("uid");
				this._uid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("online")]
		public int? online
		{
			get{ return _online; }
			set
			{
				this.OnPropertyValueChange("online");
				this._online = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("userlock")]
		public int? userlock
		{
			get{ return _userlock; }
			set
			{
				this.OnPropertyValueChange("userlock");
				this._userlock = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("roleid")]
		public int? roleid
		{
			get{ return _roleid; }
			set
			{
				this.OnPropertyValueChange("roleid");
				this._roleid = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.name,
				_.realname,
				_.pwd,
				_.regtime,
				_.endtime,
				_.lastlogdate,
				_.phone,
				_.tel,
				_.email,
				_.address,
				_.uid,
				_.online,
				_.userlock,
				_.roleid,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._name,
				this._realname,
				this._pwd,
				this._regtime,
				this._endtime,
				this._lastlogdate,
				this._phone,
				this._tel,
				this._email,
				this._address,
				this._uid,
				this._online,
				this._userlock,
				this._roleid,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "_userinfo");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "_userinfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field name = new Field("name", "_userinfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field realname = new Field("realname", "_userinfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field pwd = new Field("pwd", "_userinfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field regtime = new Field("regtime", "_userinfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field endtime = new Field("endtime", "_userinfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field lastlogdate = new Field("lastlogdate", "_userinfo", "");
            /// <summary>
			/// 手机号
			/// </summary>
			public readonly static Field phone = new Field("phone", "_userinfo", "手机号");
            /// <summary>
			/// 固话
			/// </summary>
			public readonly static Field tel = new Field("tel", "_userinfo", "固话");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field email = new Field("email", "_userinfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field address = new Field("address", "_userinfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field uid = new Field("uid", "_userinfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field online = new Field("online", "_userinfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field userlock = new Field("userlock", "_userinfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field roleid = new Field("roleid", "_userinfo", "");
        }
        #endregion
	}
}