//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace TAHB.Model
{
    /// <summary>
    /// 实体类Area。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Area")]
    [Serializable]
    public partial class Area : Entity
    {
        #region Model
		private int _Id;
		private string _RegionName;
		private string _RegionCode;
		private string _ParentCode;
		private string _Longitude;
		private string _Latitude;

		/// <summary>
		/// 序号
		/// </summary>
		[Field("Id")]
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 区域名称
		/// </summary>
		[Field("RegionName")]
		public string RegionName
		{
			get{ return _RegionName; }
			set
			{
				this.OnPropertyValueChange("RegionName");
				this._RegionName = value;
			}
		}
		/// <summary>
		/// 区域编码
		/// </summary>
		[Field("RegionCode")]
		public string RegionCode
		{
			get{ return _RegionCode; }
			set
			{
				this.OnPropertyValueChange("RegionCode");
				this._RegionCode = value;
			}
		}
		/// <summary>
		/// 父级编码
		/// </summary>
		[Field("ParentCode")]
		public string ParentCode
		{
			get{ return _ParentCode; }
			set
			{
				this.OnPropertyValueChange("ParentCode");
				this._ParentCode = value;
			}
		}
		/// <summary>
		/// 经度
		/// </summary>
		[Field("Longitude")]
		public string Longitude
		{
			get{ return _Longitude; }
			set
			{
				this.OnPropertyValueChange("Longitude");
				this._Longitude = value;
			}
		}
		/// <summary>
		/// 纬度
		/// </summary>
		[Field("Latitude")]
		public string Latitude
		{
			get{ return _Latitude; }
			set
			{
				this.OnPropertyValueChange("Latitude");
				this._Latitude = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.RegionName,
				_.RegionCode,
				_.ParentCode,
				_.Longitude,
				_.Latitude,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._RegionName,
				this._RegionCode,
				this._ParentCode,
				this._Longitude,
				this._Latitude,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Area");
            /// <summary>
			/// 序号
			/// </summary>
			public readonly static Field Id = new Field("Id", "Area", "序号");
            /// <summary>
			/// 区域名称
			/// </summary>
			public readonly static Field RegionName = new Field("RegionName", "Area", "区域名称");
            /// <summary>
			/// 区域编码
			/// </summary>
			public readonly static Field RegionCode = new Field("RegionCode", "Area", "区域编码");
            /// <summary>
			/// 父级编码
			/// </summary>
			public readonly static Field ParentCode = new Field("ParentCode", "Area", "父级编码");
            /// <summary>
			/// 经度
			/// </summary>
			public readonly static Field Longitude = new Field("Longitude", "Area", "经度");
            /// <summary>
			/// 纬度
			/// </summary>
			public readonly static Field Latitude = new Field("Latitude", "Area", "纬度");
        }
        #endregion
	}
}