//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace TAHB.Model
{
    /// <summary>
    /// 实体类statisticsLog。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("statisticsLog")]
    [Serializable]
    public partial class statisticsLog : Entity
    {
        #region Model
		private int _id;
		private string _useruid;
		private string _url;
		private long _ip;
		private DateTime? _datetime;
		private string _title;
		private string _descprition;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("useruid")]
		public string useruid
		{
			get{ return _useruid; }
			set
			{
				this.OnPropertyValueChange("useruid");
				this._useruid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("url")]
		public string url
		{
			get{ return _url; }
			set
			{
				this.OnPropertyValueChange("url");
				this._url = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ip")]
		public long ip
		{
			get{ return _ip; }
			set
			{
				this.OnPropertyValueChange("ip");
				this._ip = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("datetime")]
		public DateTime? datetime
		{
			get{ return _datetime; }
			set
			{
				this.OnPropertyValueChange("datetime");
				this._datetime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("title")]
		public string title
		{
			get{ return _title; }
			set
			{
				this.OnPropertyValueChange("title");
				this._title = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("descprition")]
		public string descprition
		{
			get{ return _descprition; }
			set
			{
				this.OnPropertyValueChange("descprition");
				this._descprition = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.useruid,
				_.url,
				_.ip,
				_.datetime,
				_.title,
				_.descprition,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._useruid,
				this._url,
				this._ip,
				this._datetime,
				this._title,
				this._descprition,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "statisticsLog");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "statisticsLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field useruid = new Field("useruid", "statisticsLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field url = new Field("url", "statisticsLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ip = new Field("ip", "statisticsLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field datetime = new Field("datetime", "statisticsLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field title = new Field("title", "statisticsLog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field descprition = new Field("descprition", "statisticsLog", "");
        }
        #endregion
	}
}