//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace TAHB.Model
{
    /// <summary>
    /// 实体类仓库记录。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("仓库记录")]
    [Serializable]
    public partial class 仓库记录 : Entity
    {
        #region Model
		private long _id;
		private string _type;
		private string _source;
		private string _explain;
		private int? _仓库转移类别;
		private DateTime? _入仓库时间;
		private DateTime? _出仓库时间;
		private DateTime? _转移出去时间;
		private string _转移连单编号;
		private string _来源企业名称;
		private string _转移到企业名称;
		private string _登记人;
		private string _登记日志;
		private string _车辆情况;
		private string _车辆照片;
		private int? _数量;
		private string _数量单位;
		private string _存储位置;
		private string _ohter;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public long id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("type")]
		public string type
		{
			get{ return _type; }
			set
			{
				this.OnPropertyValueChange("type");
				this._type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("source")]
		public string source
		{
			get{ return _source; }
			set
			{
				this.OnPropertyValueChange("source");
				this._source = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("explain")]
		public string explain
		{
			get{ return _explain; }
			set
			{
				this.OnPropertyValueChange("explain");
				this._explain = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("仓库转移类别")]
		public int? 仓库转移类别
		{
			get{ return _仓库转移类别; }
			set
			{
				this.OnPropertyValueChange("仓库转移类别");
				this._仓库转移类别 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("入仓库时间")]
		public DateTime? 入仓库时间
		{
			get{ return _入仓库时间; }
			set
			{
				this.OnPropertyValueChange("入仓库时间");
				this._入仓库时间 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("出仓库时间")]
		public DateTime? 出仓库时间
		{
			get{ return _出仓库时间; }
			set
			{
				this.OnPropertyValueChange("出仓库时间");
				this._出仓库时间 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("转移出去时间")]
		public DateTime? 转移出去时间
		{
			get{ return _转移出去时间; }
			set
			{
				this.OnPropertyValueChange("转移出去时间");
				this._转移出去时间 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("转移连单编号")]
		public string 转移连单编号
		{
			get{ return _转移连单编号; }
			set
			{
				this.OnPropertyValueChange("转移连单编号");
				this._转移连单编号 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("来源企业名称")]
		public string 来源企业名称
		{
			get{ return _来源企业名称; }
			set
			{
				this.OnPropertyValueChange("来源企业名称");
				this._来源企业名称 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("转移到企业名称")]
		public string 转移到企业名称
		{
			get{ return _转移到企业名称; }
			set
			{
				this.OnPropertyValueChange("转移到企业名称");
				this._转移到企业名称 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("登记人")]
		public string 登记人
		{
			get{ return _登记人; }
			set
			{
				this.OnPropertyValueChange("登记人");
				this._登记人 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("登记日志")]
		public string 登记日志
		{
			get{ return _登记日志; }
			set
			{
				this.OnPropertyValueChange("登记日志");
				this._登记日志 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("车辆情况")]
		public string 车辆情况
		{
			get{ return _车辆情况; }
			set
			{
				this.OnPropertyValueChange("车辆情况");
				this._车辆情况 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("车辆照片")]
		public string 车辆照片
		{
			get{ return _车辆照片; }
			set
			{
				this.OnPropertyValueChange("车辆照片");
				this._车辆照片 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("数量")]
		public int? 数量
		{
			get{ return _数量; }
			set
			{
				this.OnPropertyValueChange("数量");
				this._数量 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("数量单位")]
		public string 数量单位
		{
			get{ return _数量单位; }
			set
			{
				this.OnPropertyValueChange("数量单位");
				this._数量单位 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("存储位置")]
		public string 存储位置
		{
			get{ return _存储位置; }
			set
			{
				this.OnPropertyValueChange("存储位置");
				this._存储位置 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ohter")]
		public string ohter
		{
			get{ return _ohter; }
			set
			{
				this.OnPropertyValueChange("ohter");
				this._ohter = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.type,
				_.source,
				_.explain,
				_.仓库转移类别,
				_.入仓库时间,
				_.出仓库时间,
				_.转移出去时间,
				_.转移连单编号,
				_.来源企业名称,
				_.转移到企业名称,
				_.登记人,
				_.登记日志,
				_.车辆情况,
				_.车辆照片,
				_.数量,
				_.数量单位,
				_.存储位置,
				_.ohter,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._type,
				this._source,
				this._explain,
				this._仓库转移类别,
				this._入仓库时间,
				this._出仓库时间,
				this._转移出去时间,
				this._转移连单编号,
				this._来源企业名称,
				this._转移到企业名称,
				this._登记人,
				this._登记日志,
				this._车辆情况,
				this._车辆照片,
				this._数量,
				this._数量单位,
				this._存储位置,
				this._ohter,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "仓库记录");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field type = new Field("type", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field source = new Field("source", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field explain = new Field("explain", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 仓库转移类别 = new Field("仓库转移类别", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 入仓库时间 = new Field("入仓库时间", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 出仓库时间 = new Field("出仓库时间", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 转移出去时间 = new Field("转移出去时间", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 转移连单编号 = new Field("转移连单编号", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 来源企业名称 = new Field("来源企业名称", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 转移到企业名称 = new Field("转移到企业名称", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 登记人 = new Field("登记人", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 登记日志 = new Field("登记日志", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 车辆情况 = new Field("车辆情况", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 车辆照片 = new Field("车辆照片", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 数量 = new Field("数量", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 数量单位 = new Field("数量单位", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 存储位置 = new Field("存储位置", "仓库记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ohter = new Field("ohter", "仓库记录", "");
        }
        #endregion
	}
}