//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace TAHB.Model
{
    /// <summary>
    /// 实体类合同记录。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("合同记录")]
    [Serializable]
    public partial class 合同记录 : Entity
    {
        #region Model
		private long _id;
		private int? _合同区域;
		private int? _合同类别;
		private string _合同编号;
		private string _甲方;
		private string _乙方;
		private string _签订地点;
		private DateTime? _签订时间;
		private string _合同内容;
		private DateTime? _合同生效日期;
		private DateTime? _合同终止日期;
		private DateTime? _到期提醒时间;
		private DateTime? _结束提醒日期;
		private int? _是否到期提醒;
		private string _甲方法人代表;
		private string _已方法人代表;
		private string _甲方联系人;
		private string _乙方联系人;
		private string _甲方联系电话;
		private string _乙方联系电话;
		private string _甲方传真;
		private string _乙方传真;
		private string _甲方邮箱;
		private string _乙方邮箱;
		private string _甲方注册地;
		private string _乙方注册地;
		private string _other;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public long id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("合同区域")]
		public int? 合同区域
		{
			get{ return _合同区域; }
			set
			{
				this.OnPropertyValueChange("合同区域");
				this._合同区域 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("合同类别")]
		public int? 合同类别
		{
			get{ return _合同类别; }
			set
			{
				this.OnPropertyValueChange("合同类别");
				this._合同类别 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("合同编号")]
		public string 合同编号
		{
			get{ return _合同编号; }
			set
			{
				this.OnPropertyValueChange("合同编号");
				this._合同编号 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("甲方")]
		public string 甲方
		{
			get{ return _甲方; }
			set
			{
				this.OnPropertyValueChange("甲方");
				this._甲方 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("乙方")]
		public string 乙方
		{
			get{ return _乙方; }
			set
			{
				this.OnPropertyValueChange("乙方");
				this._乙方 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("签订地点")]
		public string 签订地点
		{
			get{ return _签订地点; }
			set
			{
				this.OnPropertyValueChange("签订地点");
				this._签订地点 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("签订时间")]
		public DateTime? 签订时间
		{
			get{ return _签订时间; }
			set
			{
				this.OnPropertyValueChange("签订时间");
				this._签订时间 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("合同内容")]
		public string 合同内容
		{
			get{ return _合同内容; }
			set
			{
				this.OnPropertyValueChange("合同内容");
				this._合同内容 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("合同生效日期")]
		public DateTime? 合同生效日期
		{
			get{ return _合同生效日期; }
			set
			{
				this.OnPropertyValueChange("合同生效日期");
				this._合同生效日期 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("合同终止日期")]
		public DateTime? 合同终止日期
		{
			get{ return _合同终止日期; }
			set
			{
				this.OnPropertyValueChange("合同终止日期");
				this._合同终止日期 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("到期提醒时间")]
		public DateTime? 到期提醒时间
		{
			get{ return _到期提醒时间; }
			set
			{
				this.OnPropertyValueChange("到期提醒时间");
				this._到期提醒时间 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("结束提醒日期")]
		public DateTime? 结束提醒日期
		{
			get{ return _结束提醒日期; }
			set
			{
				this.OnPropertyValueChange("结束提醒日期");
				this._结束提醒日期 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("是否到期提醒")]
		public int? 是否到期提醒
		{
			get{ return _是否到期提醒; }
			set
			{
				this.OnPropertyValueChange("是否到期提醒");
				this._是否到期提醒 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("甲方法人代表")]
		public string 甲方法人代表
		{
			get{ return _甲方法人代表; }
			set
			{
				this.OnPropertyValueChange("甲方法人代表");
				this._甲方法人代表 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("已方法人代表")]
		public string 已方法人代表
		{
			get{ return _已方法人代表; }
			set
			{
				this.OnPropertyValueChange("已方法人代表");
				this._已方法人代表 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("甲方联系人")]
		public string 甲方联系人
		{
			get{ return _甲方联系人; }
			set
			{
				this.OnPropertyValueChange("甲方联系人");
				this._甲方联系人 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("乙方联系人")]
		public string 乙方联系人
		{
			get{ return _乙方联系人; }
			set
			{
				this.OnPropertyValueChange("乙方联系人");
				this._乙方联系人 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("甲方联系电话")]
		public string 甲方联系电话
		{
			get{ return _甲方联系电话; }
			set
			{
				this.OnPropertyValueChange("甲方联系电话");
				this._甲方联系电话 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("乙方联系电话")]
		public string 乙方联系电话
		{
			get{ return _乙方联系电话; }
			set
			{
				this.OnPropertyValueChange("乙方联系电话");
				this._乙方联系电话 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("甲方传真")]
		public string 甲方传真
		{
			get{ return _甲方传真; }
			set
			{
				this.OnPropertyValueChange("甲方传真");
				this._甲方传真 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("乙方传真")]
		public string 乙方传真
		{
			get{ return _乙方传真; }
			set
			{
				this.OnPropertyValueChange("乙方传真");
				this._乙方传真 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("甲方邮箱")]
		public string 甲方邮箱
		{
			get{ return _甲方邮箱; }
			set
			{
				this.OnPropertyValueChange("甲方邮箱");
				this._甲方邮箱 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("乙方邮箱")]
		public string 乙方邮箱
		{
			get{ return _乙方邮箱; }
			set
			{
				this.OnPropertyValueChange("乙方邮箱");
				this._乙方邮箱 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("甲方注册地")]
		public string 甲方注册地
		{
			get{ return _甲方注册地; }
			set
			{
				this.OnPropertyValueChange("甲方注册地");
				this._甲方注册地 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("乙方注册地")]
		public string 乙方注册地
		{
			get{ return _乙方注册地; }
			set
			{
				this.OnPropertyValueChange("乙方注册地");
				this._乙方注册地 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("other")]
		public string other
		{
			get{ return _other; }
			set
			{
				this.OnPropertyValueChange("other");
				this._other = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.合同区域,
				_.合同类别,
				_.合同编号,
				_.甲方,
				_.乙方,
				_.签订地点,
				_.签订时间,
				_.合同内容,
				_.合同生效日期,
				_.合同终止日期,
				_.到期提醒时间,
				_.结束提醒日期,
				_.是否到期提醒,
				_.甲方法人代表,
				_.已方法人代表,
				_.甲方联系人,
				_.乙方联系人,
				_.甲方联系电话,
				_.乙方联系电话,
				_.甲方传真,
				_.乙方传真,
				_.甲方邮箱,
				_.乙方邮箱,
				_.甲方注册地,
				_.乙方注册地,
				_.other,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._合同区域,
				this._合同类别,
				this._合同编号,
				this._甲方,
				this._乙方,
				this._签订地点,
				this._签订时间,
				this._合同内容,
				this._合同生效日期,
				this._合同终止日期,
				this._到期提醒时间,
				this._结束提醒日期,
				this._是否到期提醒,
				this._甲方法人代表,
				this._已方法人代表,
				this._甲方联系人,
				this._乙方联系人,
				this._甲方联系电话,
				this._乙方联系电话,
				this._甲方传真,
				this._乙方传真,
				this._甲方邮箱,
				this._乙方邮箱,
				this._甲方注册地,
				this._乙方注册地,
				this._other,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "合同记录");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 合同区域 = new Field("合同区域", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 合同类别 = new Field("合同类别", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 合同编号 = new Field("合同编号", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 甲方 = new Field("甲方", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 乙方 = new Field("乙方", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 签订地点 = new Field("签订地点", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 签订时间 = new Field("签订时间", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 合同内容 = new Field("合同内容", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 合同生效日期 = new Field("合同生效日期", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 合同终止日期 = new Field("合同终止日期", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 到期提醒时间 = new Field("到期提醒时间", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 结束提醒日期 = new Field("结束提醒日期", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 是否到期提醒 = new Field("是否到期提醒", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 甲方法人代表 = new Field("甲方法人代表", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 已方法人代表 = new Field("已方法人代表", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 甲方联系人 = new Field("甲方联系人", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 乙方联系人 = new Field("乙方联系人", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 甲方联系电话 = new Field("甲方联系电话", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 乙方联系电话 = new Field("乙方联系电话", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 甲方传真 = new Field("甲方传真", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 乙方传真 = new Field("乙方传真", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 甲方邮箱 = new Field("甲方邮箱", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 乙方邮箱 = new Field("乙方邮箱", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 甲方注册地 = new Field("甲方注册地", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field 乙方注册地 = new Field("乙方注册地", "合同记录", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field other = new Field("other", "合同记录", "");
        }
        #endregion
	}
}