$axure.loadCurrentPage({
  "url":"登录页面-机构账户.html",
  "generationDate":new Date(1489416214289.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ad309e392c3d43f7b7730114749bcbc4",
    "type":"Axure:Page",
    "name":"登录页面-机构账户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF6F6F6},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6fcf330674ee4837bbd5aee3be24c6e3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":79},
            "size":{
              "width":1247,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8CD8F0}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录页面-机构账户/u0_line.png"}},
{
          "id":"64ae2e034c644ab287b2079943164f43",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'宋体 常规', '宋体'",
            "location":{
              "x":105,
              "y":23},
            "size":{
              "width":201,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be480eddc4f947ea92902f1f5b44f06a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 常规', '宋体'",
                "location":{
                  "x":105,
                  "y":23},
                "size":{
                  "width":201,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面-个人账户/u1.gif"}},
{
          "id":"61def0538a8c4567a60429f7f287e4f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 常规', '宋体'",
            "fontSize":"22px",
            "location":{
              "x":356,
              "y":38},
            "size":{
              "width":117,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7fd5a926b7643499760d645ecd58dac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 常规', '宋体'",
                "fontSize":"22px",
                "location":{
                  "x":356,
                  "y":38},
                "size":{
                  "width":117,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7169877487184dcf9d77fc819827b595",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":38},
            "size":{
              "width":10,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录页面-个人账户/u5_line.png"}},
{
          "id":"0344df74823d47488e0c78501202124f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9933,
              "opacity":1},
            "opacity":"0.65",
            "location":{
              "x":64,
              "y":85},
            "size":{
              "width":1247,
              "height":482}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab4e7e999b9040ed841f9fd5a0150899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9933,
                  "opacity":1},
                "opacity":"0.65",
                "location":{
                  "x":64,
                  "y":85},
                "size":{
                  "width":1247,
                  "height":482}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面-机构账户/u6.jpg"}},
{
          "id":"525ae9210a6c4de0b352d6a135624c98",
          "label":"dl-登录注册窗口",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":841,
              "y":136},
            "size":{
              "width":332,
              "height":353},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b0c8d7e51194bafa567a737a514f278",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":841,
                  "y":136},
                "size":{
                  "width":332,
                  "height":353},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面-个人账户/dl-登录注册窗口_u17.png"}},
{
          "id":"5f326730d1d04de6b5de7cb25879e549",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":842,
              "y":137},
            "size":{
              "width":165,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00354215c4414cc1884d338b17109071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":842,
                  "y":137},
                "size":{
                  "width":165,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录页面-个人账户",
                      "target":{
                        "targetType":"page",
                        "url":"登录页面-个人账户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录页面-机构账户/u10.png"}},
{
          "id":"d63c4369906d43c4b4743f9b5229c275",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1008,
              "y":136},
            "size":{
              "width":164,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82412475c03f44f08b2593be9d09548d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1008,
                  "y":136},
                "size":{
                  "width":164,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录页面-机构账户",
                      "target":{
                        "targetType":"page",
                        "url":"登录页面-机构账户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录页面-机构账户/u12.png"}},
{
          "id":"c10f3999aa7544e494feec0b053348b5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":876,
              "y":214},
            "size":{
              "width":39,
              "height":36}},
          "adaptiveStyles":{
}},
{
          "id":"89180519e7154bb182adb12a9e0d5e32",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":876,
              "y":271},
            "size":{
              "width":39,
              "height":36}},
          "adaptiveStyles":{
}},
{
          "id":"6fd6e0edadb44b61a4affc76b839f9c4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9,
              "opacity":1},
            "location":{
              "x":910,
              "y":214},
            "size":{
              "width":229,
              "height":36}},
          "adaptiveStyles":{
}},
{
          "id":"0877229a093841819825030db776a818",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9,
              "opacity":1},
            "location":{
              "x":910,
              "y":271},
            "size":{
              "width":229,
              "height":36}},
          "adaptiveStyles":{
}},
{
          "id":"92afa35a917f4831b4629802b4ec4a4a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":885,
              "y":223},
            "size":{
              "width":21,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f8b8cfbc2bc4fa1b9d959ad7b2ed834",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":885,
                  "y":223},
                "size":{
                  "width":21,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面-个人账户/u89.png"}},
{
          "id":"fbbd53ae00fb4528a84c0d7b9dab36ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":909,
              "y":215},
            "size":{
              "width":4,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0497aa72d5c4696869842bd1774cb2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":909,
                  "y":215},
                "size":{
                  "width":4,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面-个人账户/u91.png"}},
{
          "id":"020a831050494cf6853d2dc7875d86ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":909,
              "y":272},
            "size":{
              "width":4,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebe5235959ca4e648de3ba0b71c00ea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":909,
                  "y":272},
                "size":{
                  "width":4,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面-个人账户/u91.png"}},
{
          "id":"cbcc21d895a84bfca0f13be7c721a9da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":885,
              "y":280},
            "size":{
              "width":20,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07fb7b283b8344f1b422ab71c0c9de6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":885,
                  "y":280},
                "size":{
                  "width":20,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面-个人账户/u95.png"}},
{
          "id":"9ea0032fcec744ab923894d2b4ba49b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF016AB4,
              "opacity":1},
            "location":{
              "x":1061,
              "y":322},
            "size":{
              "width":76,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"823b1157bbf4445aad2c6a2d29ffb353",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF016AB4,
                  "opacity":1},
                "location":{
                  "x":1061,
                  "y":322},
                "size":{
                  "width":76,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebc7f1f0ae204d3e918169015ffd66fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0479D6},
            "location":{
              "x":876,
              "y":365},
            "size":{
              "width":115,
              "height":36},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"363ec227becf4a4cb8cdc1b1eeb8daa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0479D6},
                "location":{
                  "x":876,
                  "y":365},
                "size":{
                  "width":115,
                  "height":36},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面-个人账户/u101.png"}},
{
          "id":"8b3c8507254c4c66ad7502a21653349a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1021,
              "y":365},
            "size":{
              "width":116,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC2C2C2},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea825ddf6c804554aa3838575c0b1fd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1021,
                  "y":365},
                "size":{
                  "width":116,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC2C2C2},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面-个人账户/u103.png"}},
{
          "id":"e8e1aa15df434342a6fca3f1167e6714",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":540},
            "size":{
              "width":1344,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e686d6f4bc74471eb6d2efb523351687",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-10,
                  "y":540},
                "size":{
                  "width":1344,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面-个人账户/u116.png"}},
{
          "id":"da4c3e9a5a9045229aba13ee83955e35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1112,
              "y":542},
            "size":{
              "width":201,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a92dcdb413e45968e666665dea98ab9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1112,
                  "y":542},
                "size":{
                  "width":201,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面-个人账户/u118.png"}},
{
          "id":"9ad13ccb4a7547b98fd248139e50c888",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":541},
            "size":{
              "width":154,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33c5128532704d57b5c3d34a9169a72c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":62,
                  "y":541},
                "size":{
                  "width":154,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面-个人账户/u120.png"}},
{
          "id":"8496a4a284f149c58d99298a8d3b8d57",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":171,
              "y":179},
            "size":{
              "width":576,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a35c141c3d747c3bb6f587db02ac22e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":171,
                  "y":179},
                "size":{
                  "width":576,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页面-机构账户/u38.png"}},
{
          "id":"ae9639c11b514bfd8fca5ded0732fd7e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":705,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"96e9e40ba9eb4667ac8de91cd8b9e653"}]}},
  "masters":{
    "96e9e40ba9eb4667ac8de91cd8b9e653":{
      "packageId":"96e9e40ba9eb4667ac8de91cd8b9e653",
      "type":"Axure:Master",
      "name":"页头",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e80ac2f60bbe4329a83e43188d4da2da",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF6F6F6},
              "location":{
                "x":275,
                "y":100},
              "size":{
                "width":228,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7ca5746146a14473a9bdfd1e47ab790b",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":228,
                    "height":25}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"9207e44c95c64f1d80c75305b6d4c5be",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"12px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1}},
                        "selected":{
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFF6F6F6},
                      "location":{
                        "x":150,
                        "y":0},
                      "size":{
                        "width":78,
                        "height":25},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFA1A1A1}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"36c4392b4e3b43feb6d348eab0e15c1c",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"12px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}},
                            "selected":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFF6F6F6},
                          "location":{
                            "x":150,
                            "y":0},
                          "size":{
                            "width":78,
                            "height":25},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFA1A1A1}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 新窗口/标签页 打开 http://service.cnki.net/helpcenter/Html/index.html?randomNum=255",
                                "target":{
                                  "targetType":"webUrl",
                                  "urlLiteral":{
                                    "exprType":"stringLiteral",
                                    "value":"http://service.cnki.net/helpcenter/Html/index.html?randomNum=255",
                                    "stos":[]},
                                  "includeVariables":false},
                                "linkType":"new"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/登录页面-个人账户/u129.png",
                      "selected~":"images/登录页面-个人账户/u129.png",
                      "mouseOver~":"images/登录页面-个人账户/u129.png"}},
{
                    "id":"64bc6cf49dc24f01ae20afe40b1de804",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"12px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1}},
                        "selected":{
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFF6F6F6},
                      "size":{
                        "width":75,
                        "height":25},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFA1A1A1}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d1ffad417d994494a6dedce3e3db6564",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"12px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}},
                            "selected":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFF6F6F6},
                          "size":{
                            "width":75,
                            "height":25},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFA1A1A1}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/登录页面-个人账户/u125.png",
                      "selected~":"images/登录页面-个人账户/u125.png",
                      "mouseOver~":"images/登录页面-个人账户/u125.png"}},
{
                    "id":"edfb7415a17a42be9b670e2502e4642a",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"12px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1}},
                        "selected":{
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFF6F6F6},
                      "location":{
                        "x":75,
                        "y":0},
                      "size":{
                        "width":75,
                        "height":25},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFA1A1A1}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"719dc600d98946cd9d342db0c5ea4cbc",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"12px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}},
                            "selected":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFF6F6F6},
                          "location":{
                            "x":75,
                            "y":0},
                          "size":{
                            "width":75,
                            "height":25},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFA1A1A1}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 新窗口/标签页 打开 http://zhifu.cnki.net/",
                                "target":{
                                  "targetType":"webUrl",
                                  "urlLiteral":{
                                    "exprType":"stringLiteral",
                                    "value":"http://zhifu.cnki.net/",
                                    "stos":[]},
                                  "includeVariables":false},
                                "linkType":"new"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/登录页面-个人账户/u125.png",
                      "selected~":"images/登录页面-个人账户/u125.png",
                      "mouseOver~":"images/登录页面-个人账户/u125.png"}}]},
{
                "id":"f6bb1109d90740a9b3a741ec10ca0ff1",
                "label":"",
                "type":"menuObject",
                "styleType":"menuObject",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":0,
                    "y":25},
                  "size":{
                    "width":120,
                    "height":75},
                  "limbo":false,
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"875f0c8d2372440bac7c98a8a0bd9f79",
                    "label":"",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":120,
                        "height":75}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6f9df8375cf142ab971d5ee85acd5f2a",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}},
                            "selected":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFF6F6F6},
                          "size":{
                            "width":120,
                            "height":25},
                          "limbo":false,
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"79a89ce8d1c7498f8fe6c36b1ac95032",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF666666,
                                "opacity":1},
                              "stateStyles":{
                                "mouseOver":{
                                  "fontWeight":"bold",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0000FF,
                                    "opacity":1}},
                                "selected":{
                                  "fontWeight":"bold",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0000FF,
                                    "opacity":1}}},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFF6F6F6},
                              "size":{
                                "width":120,
                                "height":25},
                              "limbo":false,
                              "borderWidth":"-1",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFFFF}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/登录页面-个人账户/u133.png",
                          "selected~":"images/登录页面-个人账户/u133.png",
                          "mouseOver~":"images/登录页面-个人账户/u133.png"}},
{
                        "id":"6069689cf556464f8735f3d179ff2cbf",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}},
                            "selected":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFF6F6F6},
                          "location":{
                            "x":0,
                            "y":25},
                          "size":{
                            "width":120,
                            "height":25},
                          "limbo":false,
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"b84bb3d5ad45481b91d680f0db722ed7",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF666666,
                                "opacity":1},
                              "stateStyles":{
                                "mouseOver":{
                                  "fontWeight":"bold",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0000FF,
                                    "opacity":1}},
                                "selected":{
                                  "fontWeight":"bold",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0000FF,
                                    "opacity":1}}},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFF6F6F6},
                              "location":{
                                "x":0,
                                "y":25},
                              "size":{
                                "width":120,
                                "height":25},
                              "limbo":false,
                              "borderWidth":"-1",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFFFF}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/登录页面-个人账户/u133.png",
                          "selected~":"images/登录页面-个人账户/u133.png",
                          "mouseOver~":"images/登录页面-个人账户/u133.png"}},
{
                        "id":"04cccfa41e63498b9c11b2a09d6009b7",
                        "label":"",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontSize":"12px",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}},
                            "selected":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFF6F6F6},
                          "location":{
                            "x":0,
                            "y":50},
                          "size":{
                            "width":120,
                            "height":25},
                          "limbo":false,
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"1e5cf3505fb14f008d45a168f56f1a24",
                            "label":"",
                            "isContained":true,
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"12px",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF666666,
                                "opacity":1},
                              "stateStyles":{
                                "mouseOver":{
                                  "fontWeight":"bold",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0000FF,
                                    "opacity":1}},
                                "selected":{
                                  "fontWeight":"bold",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0000FF,
                                    "opacity":1}}},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFF6F6F6},
                              "location":{
                                "x":0,
                                "y":50},
                              "size":{
                                "width":120,
                                "height":25},
                              "limbo":false,
                              "borderWidth":"-1",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFFFF}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/登录页面-个人账户/u133.png",
                          "selected~":"images/登录页面-个人账户/u133.png",
                          "mouseOver~":"images/登录页面-个人账户/u133.png"}}]}],
                "parentCellId":"64bc6cf49dc24f01ae20afe40b1de804"}]},
{
            "id":"1a810f6d39fa4983a8e3b1224bf008e0",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":271,
                "y":106},
              "size":{
                "width":10,
                "height":13},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/登录页面-个人账户/u139_line.png"}},
{
            "id":"097527410f9c4e8897496f5b8e75dc5a",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":345,
                "y":106},
              "size":{
                "width":10,
                "height":13},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/登录页面-个人账户/u139_line.png"}},
{
            "id":"3cdbb619f56c4b78a0e75ad984b42357",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":425,
                "y":106},
              "size":{
                "width":10,
                "height":13},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/登录页面-个人账户/u139_line.png"}},
{
            "id":"7b9eccc41d3e4ebd81234491d558a2af",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF6F6F6},
              "location":{
                "x":60,
                "y":100},
              "size":{
                "width":215,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8f116302ad5f46d0a55f331e40d4abb9",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":215,
                    "height":25}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"94a7a8448f5749068f80390c348d51a1",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"12px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF92B324}},
                        "selected":{
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFF6F6F6},
                      "size":{
                        "width":66,
                        "height":25},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFA1A1A1}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9d57ab6c2e42479b94b83b78b8ad3d8b",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"12px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF92B324}},
                            "selected":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFF6F6F6},
                          "size":{
                            "width":66,
                            "height":25},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFA1A1A1}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 新窗口/标签页 打开 http://www.cnki.net/",
                                "target":{
                                  "targetType":"webUrl",
                                  "urlLiteral":{
                                    "exprType":"stringLiteral",
                                    "value":"http://www.cnki.net/",
                                    "stos":[]},
                                  "includeVariables":false},
                                "linkType":"new"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/登录页面-个人账户/u144.png",
                      "selected~":"images/登录页面-个人账户/u144.png",
                      "mouseOver~":"images/登录页面-个人账户/u144_mouseOver.png"}},
{
                    "id":"a6c9ad704859474b960b4a89cef4d1ac",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"12px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF92B324}},
                        "selected":{
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFF6F6F6},
                      "location":{
                        "x":66,
                        "y":0},
                      "size":{
                        "width":75,
                        "height":25},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFA1A1A1}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"640ac41b7a2b454fbde5aff0e697e1f2",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"12px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF92B324}},
                            "selected":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFF6F6F6},
                          "location":{
                            "x":66,
                            "y":0},
                          "size":{
                            "width":75,
                            "height":25},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFA1A1A1}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 新窗口/标签页 打开 http://m.cnki.net/mcnkidown/index_pc.html",
                                "target":{
                                  "targetType":"webUrl",
                                  "urlLiteral":{
                                    "exprType":"stringLiteral",
                                    "value":"http://m.cnki.net/mcnkidown/index_pc.html",
                                    "stos":[]},
                                  "includeVariables":false},
                                "linkType":"new"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/登录页面-个人账户/u125.png",
                      "selected~":"images/登录页面-个人账户/u125.png",
                      "mouseOver~":"images/登录页面-个人账户/u146_mouseOver.png"}},
{
                    "id":"bca2d703ab7647ce8f9e61e7c5271a48",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"12px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF92B324}},
                        "selected":{
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFF6F6F6},
                      "location":{
                        "x":141,
                        "y":0},
                      "size":{
                        "width":74,
                        "height":25},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFA1A1A1}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2afae27e6f7e4da28de822ae8c65b992",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"12px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF666666,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF92B324}},
                            "selected":{
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFF6F6F6},
                          "location":{
                            "x":141,
                            "y":0},
                          "size":{
                            "width":74,
                            "height":25},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFA1A1A1}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/登录页面-个人账户/u148.png",
                      "selected~":"images/登录页面-个人账户/u148.png",
                      "mouseOver~":"images/登录页面-个人账户/u148_mouseOver.png"}}]}]},
{
            "id":"1fbb34ee8e704edf8cdac097ad7b3fc2",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":123,
                "y":106},
              "size":{
                "width":10,
                "height":13},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/登录页面-个人账户/u139_line.png"}},
{
            "id":"9e83908d1fe24981a04f0498ed1a7334",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":194,
                "y":106},
              "size":{
                "width":10,
                "height":13},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/登录页面-个人账户/u139_line.png"}},
{
            "id":"28e5e54e2ad74ac0a09382bc79571ca7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'宋体 常规', '宋体'",
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF77D0EE},
              "location":{
                "x":503,
                "y":99},
              "size":{
                "width":60,
                "height":25},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9c02f3f7fcb24a71b8127eea95bc6180",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'宋体 常规', '宋体'",
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF77D0EE},
                  "location":{
                    "x":503,
                    "y":99},
                  "size":{
                    "width":60,
                    "height":25},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 登录页面-个人账户",
                        "target":{
                          "targetType":"page",
                          "url":"登录页面-个人账户.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/登录页面-个人账户/u152.png"}},
{
            "id":"c737cc06ad58409d9ae1f61ec8bdbc88",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'宋体 常规', '宋体'",
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFA3D075},
              "location":{
                "x":562,
                "y":99},
              "size":{
                "width":60,
                "height":25},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2196f2e370424f6ebd4e0535c05dbea2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'宋体 常规', '宋体'",
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFA3D075},
                  "location":{
                    "x":562,
                    "y":99},
                  "size":{
                    "width":60,
                    "height":25},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录页面-个人账户/u154.png"}}]}}},
  "objectPaths":{
    "6fcf330674ee4837bbd5aee3be24c6e3":{
      "scriptId":"u0"},
    "64ae2e034c644ab287b2079943164f43":{
      "scriptId":"u1"},
    "be480eddc4f947ea92902f1f5b44f06a":{
      "scriptId":"u2"},
    "61def0538a8c4567a60429f7f287e4f7":{
      "scriptId":"u3"},
    "f7fd5a926b7643499760d645ecd58dac":{
      "scriptId":"u4"},
    "7169877487184dcf9d77fc819827b595":{
      "scriptId":"u5"},
    "0344df74823d47488e0c78501202124f":{
      "scriptId":"u6"},
    "ab4e7e999b9040ed841f9fd5a0150899":{
      "scriptId":"u7"},
    "525ae9210a6c4de0b352d6a135624c98":{
      "scriptId":"u8"},
    "1b0c8d7e51194bafa567a737a514f278":{
      "scriptId":"u9"},
    "5f326730d1d04de6b5de7cb25879e549":{
      "scriptId":"u10"},
    "00354215c4414cc1884d338b17109071":{
      "scriptId":"u11"},
    "d63c4369906d43c4b4743f9b5229c275":{
      "scriptId":"u12"},
    "82412475c03f44f08b2593be9d09548d":{
      "scriptId":"u13"},
    "c10f3999aa7544e494feec0b053348b5":{
      "scriptId":"u14"},
    "89180519e7154bb182adb12a9e0d5e32":{
      "scriptId":"u15"},
    "6fd6e0edadb44b61a4affc76b839f9c4":{
      "scriptId":"u16"},
    "0877229a093841819825030db776a818":{
      "scriptId":"u17"},
    "92afa35a917f4831b4629802b4ec4a4a":{
      "scriptId":"u18"},
    "5f8b8cfbc2bc4fa1b9d959ad7b2ed834":{
      "scriptId":"u19"},
    "fbbd53ae00fb4528a84c0d7b9dab36ea":{
      "scriptId":"u20"},
    "c0497aa72d5c4696869842bd1774cb2b":{
      "scriptId":"u21"},
    "020a831050494cf6853d2dc7875d86ea":{
      "scriptId":"u22"},
    "ebe5235959ca4e648de3ba0b71c00ea4":{
      "scriptId":"u23"},
    "cbcc21d895a84bfca0f13be7c721a9da":{
      "scriptId":"u24"},
    "07fb7b283b8344f1b422ab71c0c9de6d":{
      "scriptId":"u25"},
    "9ea0032fcec744ab923894d2b4ba49b9":{
      "scriptId":"u26"},
    "823b1157bbf4445aad2c6a2d29ffb353":{
      "scriptId":"u27"},
    "ebc7f1f0ae204d3e918169015ffd66fd":{
      "scriptId":"u28"},
    "363ec227becf4a4cb8cdc1b1eeb8daa0":{
      "scriptId":"u29"},
    "8b3c8507254c4c66ad7502a21653349a":{
      "scriptId":"u30"},
    "ea825ddf6c804554aa3838575c0b1fd8":{
      "scriptId":"u31"},
    "e8e1aa15df434342a6fca3f1167e6714":{
      "scriptId":"u32"},
    "e686d6f4bc74471eb6d2efb523351687":{
      "scriptId":"u33"},
    "da4c3e9a5a9045229aba13ee83955e35":{
      "scriptId":"u34"},
    "1a92dcdb413e45968e666665dea98ab9":{
      "scriptId":"u35"},
    "9ad13ccb4a7547b98fd248139e50c888":{
      "scriptId":"u36"},
    "33c5128532704d57b5c3d34a9169a72c":{
      "scriptId":"u37"},
    "8496a4a284f149c58d99298a8d3b8d57":{
      "scriptId":"u38"},
    "4a35c141c3d747c3bb6f587db02ac22e":{
      "scriptId":"u39"},
    "ae9639c11b514bfd8fca5ded0732fd7e":{
      "scriptId":"u40",
      "e80ac2f60bbe4329a83e43188d4da2da":{
        "scriptId":"u41"},
      "7ca5746146a14473a9bdfd1e47ab790b":{
        "scriptId":"u42"},
      "64bc6cf49dc24f01ae20afe40b1de804":{
        "scriptId":"u43"},
      "d1ffad417d994494a6dedce3e3db6564":{
        "scriptId":"u44"},
      "edfb7415a17a42be9b670e2502e4642a":{
        "scriptId":"u45"},
      "719dc600d98946cd9d342db0c5ea4cbc":{
        "scriptId":"u46"},
      "9207e44c95c64f1d80c75305b6d4c5be":{
        "scriptId":"u47"},
      "36c4392b4e3b43feb6d348eab0e15c1c":{
        "scriptId":"u48"},
      "f6bb1109d90740a9b3a741ec10ca0ff1":{
        "scriptId":"u49"},
      "875f0c8d2372440bac7c98a8a0bd9f79":{
        "scriptId":"u50"},
      "6f9df8375cf142ab971d5ee85acd5f2a":{
        "scriptId":"u51"},
      "79a89ce8d1c7498f8fe6c36b1ac95032":{
        "scriptId":"u52"},
      "6069689cf556464f8735f3d179ff2cbf":{
        "scriptId":"u53"},
      "b84bb3d5ad45481b91d680f0db722ed7":{
        "scriptId":"u54"},
      "04cccfa41e63498b9c11b2a09d6009b7":{
        "scriptId":"u55"},
      "1e5cf3505fb14f008d45a168f56f1a24":{
        "scriptId":"u56"},
      "1a810f6d39fa4983a8e3b1224bf008e0":{
        "scriptId":"u57"},
      "097527410f9c4e8897496f5b8e75dc5a":{
        "scriptId":"u58"},
      "3cdbb619f56c4b78a0e75ad984b42357":{
        "scriptId":"u59"},
      "7b9eccc41d3e4ebd81234491d558a2af":{
        "scriptId":"u60"},
      "8f116302ad5f46d0a55f331e40d4abb9":{
        "scriptId":"u61"},
      "94a7a8448f5749068f80390c348d51a1":{
        "scriptId":"u62"},
      "9d57ab6c2e42479b94b83b78b8ad3d8b":{
        "scriptId":"u63"},
      "a6c9ad704859474b960b4a89cef4d1ac":{
        "scriptId":"u64"},
      "640ac41b7a2b454fbde5aff0e697e1f2":{
        "scriptId":"u65"},
      "bca2d703ab7647ce8f9e61e7c5271a48":{
        "scriptId":"u66"},
      "2afae27e6f7e4da28de822ae8c65b992":{
        "scriptId":"u67"},
      "1fbb34ee8e704edf8cdac097ad7b3fc2":{
        "scriptId":"u68"},
      "9e83908d1fe24981a04f0498ed1a7334":{
        "scriptId":"u69"},
      "28e5e54e2ad74ac0a09382bc79571ca7":{
        "scriptId":"u70"},
      "9c02f3f7fcb24a71b8127eea95bc6180":{
        "scriptId":"u71"},
      "c737cc06ad58409d9ae1f61ec8bdbc88":{
        "scriptId":"u72"},
      "2196f2e370424f6ebd4e0535c05dbea2":{
        "scriptId":"u73"}}}});