$axure.loadCurrentPage({
  "url":"基本资料-编辑.html",
  "generationDate":new Date(1489416225971.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d2014dfd15eb4e73aec1d871e7108e16",
    "type":"Axure:Page",
    "name":"基本资料-编辑",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0a92d2405c984f6cbec5410d4359c953",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1193,
              "height":615}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a21d1d38d6d4508a790f9d12c5cf8b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1193,
                  "height":615}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本资料-编辑/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0a92d2405c984f6cbec5410d4359c953":{
      "scriptId":"u0"},
    "2a21d1d38d6d4508a790f9d12c5cf8b7":{
      "scriptId":"u1"}}});