$axure.loadCurrentPage({
  "url":"个人中心结构图.html",
  "generationDate":new Date(1489991709639.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"68570507d98c4742868dd5d44f8d28fd",
    "type":"Axure:Page",
    "name":"个人中心结构图",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"36c69846fde544168363befe5fbc7b35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1342,
              "height":3198}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1bf38b059c141cdb78f52ec44ab5762",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1342,
                  "height":3198}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心结构图/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "36c69846fde544168363befe5fbc7b35":{
      "scriptId":"u0"},
    "e1bf38b059c141cdb78f52ec44ab5762":{
      "scriptId":"u1"}}});