//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69zg.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class C_directories
    {
        public int id { get; set; }
        [Display(Name = "废弃类别")]
        public string type { get; set; }
        [Display(Name = "行业来源")]
        public string source { get; set; }
        [Display(Name = "废弃代码")]
        public string code { get; set; }
        [Display(Name = "危险废物")]
        public string explain { get; set; }
        [Display(Name = "危险特性")]
        public string character { get; set; }
        [Display(Name = "备注说明")]
        public string other { get; set; }
    }
}
