//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69zg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_functioninfo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string displayname { get; set; }
        public string actionname { get; set; }
        public string controllername { get; set; }
        public string description { get; set; }
        public Nullable<int> fatherid { get; set; }
        public Nullable<int> level { get; set; }
    }
}
