//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69zg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_userinfo
    {
        public long id { get; set; }
        public string name { get; set; }
        public string realname { get; set; }
        public string pwd { get; set; }
        public System.DateTime regtime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<System.DateTime> lastlogdate { get; set; }
        public string phone { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string uid { get; set; }
        public Nullable<byte> online { get; set; }
        public Nullable<byte> userlock { get; set; }
        public Nullable<int> roleid { get; set; }
    }
}
