//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69zg.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesSqlConnStr : DbContext
    {
        public EntitiesSqlConnStr()
            : base("name=EntitiesSqlConnStr")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_directories> C_directories { get; set; }
        public virtual DbSet<C_freedirectories> C_freedirectories { get; set; }
        public virtual DbSet<C_functioninfo> C_functioninfo { get; set; }
        public virtual DbSet<C_roleinfo> C_roleinfo { get; set; }
        public virtual DbSet<C_userinfo> C_userinfo { get; set; }
        public virtual DbSet<statisticsLog> statisticsLog { get; set; }
        public virtual DbSet<statisticsUser> statisticsUser { get; set; }
        public virtual DbSet<仓库记录> 仓库记录 { get; set; }
        public virtual DbSet<仓库转移类别> 仓库转移类别 { get; set; }
        public virtual DbSet<合同记录> 合同记录 { get; set; }
        public virtual DbSet<合同类别> 合同类别 { get; set; }
        public virtual DbSet<区域代码> 区域代码 { get; set; }
    }
}
