//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69zg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class statisticsLog
    {
        public int id { get; set; }
        public string useruid { get; set; }
        public string url { get; set; }
        public long ip { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string title { get; set; }
        public string descprition { get; set; }
    }
}
