//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69zg.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class 仓库转移类别
    {
        public int id { get; set; }
        
        [Display(Name ="名称")]
        public string name { get; set; }
        [Display(Name = "备注")]
        public string other { get; set; }
    }
}
