//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69zg.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class 仓库记录
    {
        public long id { get; set; }
        [Display(Name ="废弃类别")]
        public string type { get; set; }
        [Display(Name = "行业来源")]
        public string source { get; set; }
        [Display(Name = "危险废物")]
        public string explain { get; set; }
        public Nullable<int> 仓库转移类别 { get; set; }
        public Nullable<System.DateTime> 入仓库时间 { get; set; }
        public Nullable<System.DateTime> 出仓库时间 { get; set; }
        public Nullable<System.DateTime> 转移出去时间 { get; set; }
        public string 转移连单编号 { get; set; }
        public string 来源企业名称 { get; set; }
        public string 转移到企业名称 { get; set; }
        public string 登记人 { get; set; }
        public string 登记日志 { get; set; }
        public string 车辆情况 { get; set; }
        public string 车辆照片 { get; set; }
        public Nullable<int> 数量 { get; set; }
        public string 数量单位 { get; set; }
        public string 存储位置 { get; set; }
        public string ohter { get; set; }
    }
}
