//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _69zg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 合同记录
    {
        public long id { get; set; }
        public Nullable<int> 合同区域 { get; set; }
        public Nullable<int> 合同类别 { get; set; }
        public string 合同编号 { get; set; }
        public string 甲方 { get; set; }
        public string 乙方 { get; set; }
        public string 签订地点 { get; set; }
        public Nullable<System.DateTime> 签订时间 { get; set; }
        public string 合同内容 { get; set; }
        public Nullable<System.DateTime> 合同生效日期 { get; set; }
        public Nullable<System.DateTime> 合同终止日期 { get; set; }
        public Nullable<System.DateTime> 到期提醒时间 { get; set; }
        public Nullable<System.DateTime> 结束提醒日期 { get; set; }
        public Nullable<byte> 是否到期提醒 { get; set; }
        public string 甲方法人代表 { get; set; }
        public string 已方法人代表 { get; set; }
        public string 甲方联系人 { get; set; }
        public string 乙方联系人 { get; set; }
        public string 甲方联系电话 { get; set; }
        public string 乙方联系电话 { get; set; }
        public string 甲方传真 { get; set; }
        public string 乙方传真 { get; set; }
        public string 甲方邮箱 { get; set; }
        public string 乙方邮箱 { get; set; }
        public string 甲方注册地 { get; set; }
        public string 乙方注册地 { get; set; }
        public string other { get; set; }
    }
}
