$axure.loadCurrentPage({
  "url":"登录下载流程图.html",
  "generationDate":new Date(1489991709732.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fc08c85bbc5540849cf16b697d5c4dbb",
    "type":"Axure:Page",
    "name":"登录下载流程图",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b6b94e87078f4dc9b1c9675d8735a3b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-20,
              "y":-20},
            "size":{
              "width":628,
              "height":760},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da1760cf5d194a60afd76f0523f27fc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-20,
                  "y":-20},
                "size":{
                  "width":628,
                  "height":760},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录下载流程图/u0.png"}},
{
          "id":"6da582ddd7f7424e9f0b94da8aeda6ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":778,
              "y":0},
            "size":{
              "width":1,
              "height":941},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e722217f4d3342759868baf3241b46a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":778,
                  "y":0},
                "size":{
                  "width":1,
                  "height":941},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录下载流程图/u2.png"}},
{
          "id":"4abd4d9c55694ad3baf233672b3cd514",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":778,
              "y":941},
            "size":{
              "width":1,
              "height":1045},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f0cd19461594c9cad289429e0983a87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":778,
                  "y":941},
                "size":{
                  "width":1,
                  "height":1045},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录下载流程图/u4.png"}},
{
          "id":"2b9fc125858841f7a8b2c4812b9fbdf8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1986},
            "size":{
              "width":778,
              "height":1},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a45a242fcef14d3a8e100d384d3db25c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1986},
                "size":{
                  "width":778,
                  "height":1},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录下载流程图/u6.png"}},
{
          "id":"56ea731facaf4a9c8a6c340405809d83",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":693},
            "size":{
              "width":1099,
              "height":959},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5210d88b3054d13b2b10a67fe3e8794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":693},
                "size":{
                  "width":1099,
                  "height":959},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录下载流程图/u8.png"}},
{
          "id":"ff79ff54d2df40639f2d3ebc89eae54d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1347,
              "y":2000},
            "size":{
              "width":1,
              "height":1176},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0140e642124c478699c44773214c09c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1347,
                  "y":2000},
                "size":{
                  "width":1,
                  "height":1176},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录下载流程图/u10.png"}},
{
          "id":"000e17a7b76841e4b41265d551dcb798",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1347,
              "y":3176},
            "size":{
              "width":1,
              "height":810},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dd416599754480cb917c1292c8396c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1347,
                  "y":3176},
                "size":{
                  "width":1,
                  "height":810},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录下载流程图/u12.png"}},
{
          "id":"411e2fb008d74f46bfcabbf6e5b5a549",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":778,
              "y":1986},
            "size":{
              "width":1348,
              "height":1},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8513470a238c4ef9b30e01e029afef68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":778,
                  "y":1986},
                "size":{
                  "width":1348,
                  "height":1},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录下载流程图/u14.png"}},
{
          "id":"7d4f622782cd401890ea30d9a546b4bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2126,
              "y":0},
            "size":{
              "width":1,
              "height":62},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c9e5f9a35904c179832f06fbbff080b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2126,
                  "y":0},
                "size":{
                  "width":1,
                  "height":62},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录下载流程图/u16.png"}},
{
          "id":"532f9954b74641ff9f39060597869ced",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2126,
              "y":62},
            "size":{
              "width":1,
              "height":1987},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"913685351f704fe58f00532fd4721d0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2126,
                  "y":62},
                "size":{
                  "width":1,
                  "height":1987},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录下载流程图/u18.png"}},
{
          "id":"f7b6a12cb3684562a00fc566355a0c57",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-80,
              "y":1609},
            "size":{
              "width":620,
              "height":832},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef90274e6e4e4adf9f0568a995d9b8b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-80,
                  "y":1609},
                "size":{
                  "width":620,
                  "height":832},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录下载流程图/u20.png"}},
{
          "id":"f9542311190c45a29b55aa3ca4cf0b09",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-181,
              "y":2396},
            "size":{
              "width":1081,
              "height":650},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5974743eabb6423caa29186b590bb80f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-181,
                  "y":2396},
                "size":{
                  "width":1081,
                  "height":650},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录下载流程图/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b6b94e87078f4dc9b1c9675d8735a3b1":{
      "scriptId":"u0"},
    "da1760cf5d194a60afd76f0523f27fc4":{
      "scriptId":"u1"},
    "6da582ddd7f7424e9f0b94da8aeda6ec":{
      "scriptId":"u2"},
    "e722217f4d3342759868baf3241b46a6":{
      "scriptId":"u3"},
    "4abd4d9c55694ad3baf233672b3cd514":{
      "scriptId":"u4"},
    "2f0cd19461594c9cad289429e0983a87":{
      "scriptId":"u5"},
    "2b9fc125858841f7a8b2c4812b9fbdf8":{
      "scriptId":"u6"},
    "a45a242fcef14d3a8e100d384d3db25c":{
      "scriptId":"u7"},
    "56ea731facaf4a9c8a6c340405809d83":{
      "scriptId":"u8"},
    "e5210d88b3054d13b2b10a67fe3e8794":{
      "scriptId":"u9"},
    "ff79ff54d2df40639f2d3ebc89eae54d":{
      "scriptId":"u10"},
    "0140e642124c478699c44773214c09c8":{
      "scriptId":"u11"},
    "000e17a7b76841e4b41265d551dcb798":{
      "scriptId":"u12"},
    "2dd416599754480cb917c1292c8396c8":{
      "scriptId":"u13"},
    "411e2fb008d74f46bfcabbf6e5b5a549":{
      "scriptId":"u14"},
    "8513470a238c4ef9b30e01e029afef68":{
      "scriptId":"u15"},
    "7d4f622782cd401890ea30d9a546b4bb":{
      "scriptId":"u16"},
    "6c9e5f9a35904c179832f06fbbff080b":{
      "scriptId":"u17"},
    "532f9954b74641ff9f39060597869ced":{
      "scriptId":"u18"},
    "913685351f704fe58f00532fd4721d0a":{
      "scriptId":"u19"},
    "f7b6a12cb3684562a00fc566355a0c57":{
      "scriptId":"u20"},
    "ef90274e6e4e4adf9f0568a995d9b8b3":{
      "scriptId":"u21"},
    "f9542311190c45a29b55aa3ca4cf0b09":{
      "scriptId":"u22"},
    "5974743eabb6423caa29186b590bb80f":{
      "scriptId":"u23"}}});